### ISSUE TITLE
Parameters for detecting small-scale intra-species synteny? 

### ISSUE THREAD

**Issue by zhaotao1987** [bcgsc/ntSynt#46]
![Uploading 20240606210546.png…]()
Thanks for developing this novel tool, I installed and did a test today, I would like to use this tool for detecting syntenic or alletic contigs within the genome. For example, if I have a dotplot like the following, it would be nice if ntSynt can treat these colored contigs as syntenic,  I tried with -d 5, and did not get any syntenic regions, actually the contigs I use is a tetraploid genome, which should contain groups of syntenic contigs.

**Comment by lcoombe** [comment]
Hi @zhaotao1987,

I'm not sure if it didn't upload correctly on your end, but I'm unfortunately not able to see your image!

Just to check - is your tetraploid assembly phased, or all together in a single fasta file? You are right that if you are just specifying the single file, ntSynt currently looks for synteny blocks across different genome files, not within a genome file. For example, I have done runs in the past using diploid assemblies, but supplied each haplotype as separate genome files, and ntSynt successfully computed synteny there. So, if you are able to do that separation, that would be the solution. 
It is definitely on our radar to look at inter-genomic synteny (within a given genome assembly file), but that isn't a feature that we currently have.

Thank you for your interest in ntSynt!
Lauren

**Comment by zhaotao1987** [comment]
![20240606210546](https://github.com/bcgsc/ntSynt/assets/16197676/b309e06c-6531-48fa-b070-4282a8dc0db7)
Sorry, I re-uploaded. It's just a partial dotplot, showing that there are multiple alletic contigs. It's not phased, I was thinking using your tool and HiC tools to help phasing. Yes, intra-genome synteny will be a great implementation, and can be used for whole genome duplication inferences and so on.  I found your tool currently can only find very well synteny, I mean the chromosome lengths are very comparable in different genomes, that is what we say as macrosynteny. But I think microsynteny, local genomic contexts identification would be a great improvement.

**Comment by lcoombe** [comment]
Thanks for the feedback!
Indeed, ntSynt is currently well-suited to detecting macrosynteny across different species. But we will certainly look at finer-grain microsynteny and intra-genomic synteny detection for future features!
